# Generated by Django 3.2.9 on 2021-11-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternalStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameDepart', models.CharField(db_index=True, max_length=40, verbose_name='Отделение')),
                ('TotalBeds', models.IntegerField(verbose_name='Всего коек')),
                ('UsedBeds', models.IntegerField(verbose_name='Занято коек')),
                ('UnusedBeds', models.IntegerField(verbose_name='Свободно коек')),
            ],
            options={
                'verbose_name': 'Внутренняя структура',
                'verbose_name_plural': 'Внутренняя структура',
                'ordering': ['NameDepart'],
            },
        ),
    ]
