# Generated by Django 3.2.9 on 2021-11-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InternalStructure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_result', models.CharField(db_index=True, max_length=40, verbose_name='Результат лечения')),
            ],
            options={
                'verbose_name': 'Результат лечения',
                'verbose_name_plural': 'Результат лечения',
                'ordering': ['treatment_result'],
            },
        ),
    ]
