# Generated by Django 3.2.9 on 2021-11-30 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InternalStructure', '0002_treatmentresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anesthesia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anesthesia', models.CharField(db_index=True, max_length=40, verbose_name='Анестезия')),
            ],
            options={
                'verbose_name': 'Анестезия',
                'verbose_name_plural': 'Анестезия',
                'ordering': ['anesthesia'],
            },
        ),
        migrations.CreateModel(
            name='Autopsy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autopsy', models.CharField(db_index=True, max_length=40, verbose_name='Вскрытие')),
            ],
            options={
                'verbose_name': 'Вскрытие',
                'verbose_name_plural': 'Вскрытие',
                'ordering': ['autopsy'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_time', models.CharField(db_index=True, max_length=40, verbose_name='Сроки доставки')),
            ],
            options={
                'verbose_name': 'Сроки доставки',
                'verbose_name_plural': 'Сроки доставки',
                'ordering': ['delivery_time'],
            },
        ),
        migrations.CreateModel(
            name='DifferenceAutopsy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difference_autopsy', models.CharField(db_index=True, max_length=40, verbose_name='Расхождение при вскрытии')),
            ],
            options={
                'verbose_name': 'Расхождение при вскрытии',
                'verbose_name_plural': 'Расхождение при вскрытии',
                'ordering': ['difference_autopsy'],
            },
        ),
        migrations.CreateModel(
            name='Financing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financing', models.CharField(db_index=True, max_length=40, verbose_name='Финансирование')),
            ],
            options={
                'verbose_name': 'Финансирование',
                'verbose_name_plural': 'Финансирование',
                'ordering': ['financing'],
            },
        ),
        migrations.CreateModel(
            name='GroupOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_operation', models.CharField(db_index=True, max_length=40, verbose_name='Группы операций')),
            ],
            options={
                'verbose_name': 'Группы операций',
                'verbose_name_plural': 'Группы операций',
                'ordering': ['group_operation'],
            },
        ),
        migrations.CreateModel(
            name='MedicalInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_institution', models.CharField(db_index=True, max_length=40, verbose_name='Медицинское учреждение')),
            ],
            options={
                'verbose_name': 'Медицинское учреждение',
                'verbose_name_plural': 'Медицинские учреждения',
                'ordering': ['medical_institution'],
            },
        ),
        migrations.CreateModel(
            name='Pregnancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnancy', models.CharField(db_index=True, max_length=40, verbose_name='Беременность')),
            ],
            options={
                'verbose_name': 'Беременность',
                'verbose_name_plural': 'Беременность',
                'ordering': ['pregnancy'],
            },
        ),
        migrations.CreateModel(
            name='SocialStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_status', models.CharField(db_index=True, max_length=40, verbose_name='Социальный статус')),
            ],
            options={
                'verbose_name': 'Социальный статус',
                'verbose_name_plural': 'Социальный статус',
                'ordering': ['social_status'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_outcome', models.CharField(db_index=True, max_length=40, verbose_name='Исход лечения')),
            ],
            options={
                'verbose_name': 'Исход лечения',
                'verbose_name_plural': 'Исход лечения',
                'ordering': ['treatment_outcome'],
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination', models.CharField(db_index=True, max_length=40, verbose_name='Прививка')),
            ],
            options={
                'verbose_name': 'Прививка',
                'verbose_name_plural': 'Прививки',
                'ordering': ['vaccination'],
            },
        ),
        migrations.CreateModel(
            name='WhereDischarged',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where_discharged', models.CharField(db_index=True, max_length=40, verbose_name='Куда выписан')),
            ],
            options={
                'verbose_name': 'Куда выписан',
                'verbose_name_plural': 'Куда выписан',
                'ordering': ['where_discharged'],
            },
        ),
        migrations.CreateModel(
            name='WhoDirected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_directed', models.CharField(db_index=True, max_length=40, verbose_name='Кто направил')),
            ],
            options={
                'verbose_name': 'Кто направил',
                'verbose_name_plural': 'Кто направил',
                'ordering': ['who_directed'],
            },
        ),
        migrations.CreateModel(
            name='NameOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_operation', models.CharField(db_index=True, max_length=40, verbose_name='Наименование операций')),
                ('group_operation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='InternalStructure.groupoperation', verbose_name='Группа операций')),
            ],
            options={
                'verbose_name': 'Наименование операций',
                'verbose_name_plural': 'Наименование операций',
                'ordering': ['name_operation'],
            },
        ),
        migrations.CreateModel(
            name='ListOfDoctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40, verbose_name='ФИО')),
                ('service_number', models.IntegerField(verbose_name='Табельный номер')),
                ('specialization', models.CharField(max_length=40, verbose_name='Специализация')),
                ('depart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='InternalStructure.internalstructure', verbose_name='Отделение')),
            ],
            options={
                'verbose_name': 'Список врачей',
                'verbose_name_plural': 'Список врачей',
                'ordering': ['full_name'],
            },
        ),
    ]
