# Generated by Django 3.2.9 on 2021-12-11 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InternalStructure', '0003_anesthesia_autopsy_deliverytime_differenceautopsy_financing_groupoperation_listofdoctors_medicalinst'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TreatmentOutcome',
        ),
    ]
