# Generated by Django 3.2.9 on 2021-11-24 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('InternalStructure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListPatPageTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(db_index=True, verbose_name='Дата')),
                ('History', models.IntegerField(verbose_name='История болезни')),
                ('FNL', models.CharField(max_length=40, verbose_name='ФИО, поступил')),
                ('TransferFrom', models.CharField(max_length=40, verbose_name='ФИО, из других отделений')),
                ('Release', models.CharField(max_length=40, verbose_name='ФИО, выписан')),
                ('ReleaseTo', models.CharField(max_length=40, verbose_name='ФИО, в другие отделения')),
                ('ReleaseToDepart', models.CharField(max_length=40, verbose_name='ФИО, в другие стационары')),
                ('Die', models.CharField(max_length=40, verbose_name='ФИО, умер')),
                ('Depart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='InternalStructure.internalstructure')),
            ],
            options={
                'verbose_name': 'Лист движения пациентов по фамилиям',
                'verbose_name_plural': 'Лист движения пациентов по фамилиям',
                'ordering': ['-Date'],
            },
        ),
        migrations.CreateModel(
            name='ListPatPageOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(db_index=True, verbose_name='Дата')),
                ('OnStartDay', models.IntegerField(verbose_name='Начало дня')),
                ('Receive', models.IntegerField(verbose_name='Поступило ')),
                ('TransferFrom', models.IntegerField(verbose_name='Переведено из других отделений')),
                ('TransferTo', models.IntegerField(verbose_name='Переведено в другие отделения')),
                ('ReleaseTotal', models.IntegerField(verbose_name='Выписано всего')),
                ('RelTotalTo', models.IntegerField(verbose_name='Выписано в другие отделения')),
                ('Die', models.IntegerField(verbose_name='Умерло')),
                ('Remain', models.IntegerField(verbose_name='Осталось')),
                ('Depart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='InternalStructure.internalstructure')),
            ],
            options={
                'verbose_name': 'Лист движения пациентов',
                'verbose_name_plural': 'Лист движения пациентов',
                'ordering': ['-Date'],
            },
        ),
    ]
