# Generated by Django 3.2.9 on 2021-11-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListPatPageOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(db_index=True, verbose_name='Дата')),
                ('OnStartDay', models.IntegerField(verbose_name='Начало дня')),
                ('Receive', models.IntegerField(verbose_name='Поступило ')),
                ('TransferFrom', models.IntegerField(verbose_name='Переведено из других отделений')),
                ('TransferTo', models.IntegerField(verbose_name='Переведено в другие отделения')),
                ('ReleaseTotal', models.IntegerField(verbose_name='Выписано всего')),
                ('RelTotalTo', models.IntegerField(verbose_name='Выписано в другие отделения')),
                ('Die', models.IntegerField(verbose_name='Умерло')),
                ('Remain', models.IntegerField(verbose_name='Осталось')),
            ],
            options={
                'verbose_name': 'Лист движения пациентов',
                'verbose_name_plural': 'Лист движения пациентов',
                'ordering': ['-Date'],
            },
        ),
    ]
