# Generated by Django 3.2.9 on 2021-11-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ListOfPatients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListPatPageTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(db_index=True, verbose_name='Дата')),
                ('FNL', models.CharField(max_length=40, verbose_name='ФИО, поступил')),
                ('TransferFrom', models.CharField(max_length=40, verbose_name='ФИО, из других отделений')),
                ('Release', models.CharField(max_length=40, verbose_name='ФИО, выписан')),
                ('ReleaseTo', models.CharField(max_length=40, verbose_name='ФИО, в другие отделения')),
                ('ReleaseToDepart', models.CharField(max_length=40, verbose_name='ФИО, в другие стационары')),
                ('Die', models.CharField(max_length=40, verbose_name='ФИО, умер')),
            ],
            options={
                'verbose_name': 'Лист движения пациентов по фамилиям',
                'verbose_name_plural': 'Лист движения пациентов по фамилиям',
                'ordering': ['-Date'],
            },
        ),
    ]
