# Generated by Django 3.2.9 on 2021-11-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ListOfPatients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listpatpagetwo',
            name='History',
            field=models.CharField(max_length=40, verbose_name='История болезни'),
        ),
    ]
