# Generated by Django 3.2.9 on 2021-11-30 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InternalStructure', '0003_anesthesia_autopsy_deliverytime_differenceautopsy_financing_groupoperation_listofdoctors_medicalinst'),
        ('ListOfPatients', '0002_alter_listpatpagetwo_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListPatView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.CharField(max_length=40, verbose_name='История болезни')),
                ('full_name', models.CharField(max_length=40, verbose_name='ФИО')),
                ('date_arrived', models.DateField(db_index=True, verbose_name='Дата поступления')),
                ('date_release', models.DateField(db_index=True, verbose_name='Дата выписки')),
                ('arrived_from_depart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_depart', to='InternalStructure.internalstructure', verbose_name='Поступил из отделения')),
                ('arrived_from_hosp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_hosp', to='InternalStructure.medicalinstitution', verbose_name='Поступил из другого МУ')),
                ('depart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depart', to='InternalStructure.internalstructure', verbose_name='Отделение')),
                ('transfer_to_depart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_depart', to='InternalStructure.internalstructure', verbose_name='Переведен в другое отделение')),
                ('transfer_to_hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_hosp', to='InternalStructure.medicalinstitution', verbose_name='Поступил из другого МУ')),
                ('treatment_result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='InternalStructure.treatmentresult', verbose_name='Результат лечения')),
            ],
            options={
                'verbose_name': 'Список пациентов',
                'verbose_name_plural': 'Список пациентов',
                'ordering': ['-date_arrived'],
            },
        ),
    ]
