# Generated by Django 3.2.9 on 2021-12-11 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InternalStructure', '0004_delete_treatmentoutcome'),
        ('ListOfPatients', '0003_listpatview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listpatview',
            name='transfer_to_hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_hosp', to='InternalStructure.medicalinstitution', verbose_name='Переведен в дрогое МУ'),
        ),
    ]
