# Generated by Django 3.2.9 on 2021-12-11 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ListOfPatients', '0004_alter_listpatview_transfer_to_hospital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listpatview',
            old_name='date_release',
            new_name='date_released',
        ),
    ]
