# Generated by Django 3.2.9 on 2021-12-11 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ListOfPatients', '0005_rename_date_release_listpatview_date_released'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listpatpageone',
            options={'ordering': ['-date'], 'verbose_name': 'Лист движения пациентов', 'verbose_name_plural': 'Лист движения пациентов'},
        ),
        migrations.AlterModelOptions(
            name='listpatpagetwo',
            options={'ordering': ['-date'], 'verbose_name': 'Лист движения пациентов по фамилиям', 'verbose_name_plural': 'Лист движения пациентов по фамилиям'},
        ),
        migrations.RenameField(
            model_name='listpatpageone',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='listpatpageone',
            old_name='Depart',
            new_name='depart',
        ),
        migrations.RenameField(
            model_name='listpatpageone',
            old_name='Die',
            new_name='die',
        ),
        migrations.RenameField(
            model_name='listpatpageone',
            old_name='OnStartDay',
            new_name='on_start_day',
        ),
        migrations.RenameField(
            model_name='listpatpageone',
            old_name='Receive',
            new_name='receive',
        ),
        migrations.RenameField(
            model_name='listpatpageone',
            old_name='RelTotalTo',
            new_name='rel_total_to',
        ),
        migrations.RenameField(
            model_name='listpatpageone',
            old_name='ReleaseTotal',
            new_name='release_total',
        ),
        migrations.RenameField(
            model_name='listpatpageone',
            old_name='Remain',
            new_name='remain',
        ),
        migrations.RenameField(
            model_name='listpatpageone',
            old_name='TransferFrom',
            new_name='transfer_from',
        ),
        migrations.RenameField(
            model_name='listpatpageone',
            old_name='TransferTo',
            new_name='transfer_to',
        ),
        migrations.RenameField(
            model_name='listpatpagetwo',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='listpatpagetwo',
            old_name='Depart',
            new_name='depart',
        ),
        migrations.RenameField(
            model_name='listpatpagetwo',
            old_name='Die',
            new_name='die',
        ),
        migrations.RenameField(
            model_name='listpatpagetwo',
            old_name='FNL',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='listpatpagetwo',
            old_name='History',
            new_name='history',
        ),
        migrations.RenameField(
            model_name='listpatpagetwo',
            old_name='Release',
            new_name='release',
        ),
        migrations.RenameField(
            model_name='listpatpagetwo',
            old_name='ReleaseTo',
            new_name='release_to',
        ),
        migrations.RenameField(
            model_name='listpatpagetwo',
            old_name='ReleaseToDepart',
            new_name='release_to_depart',
        ),
        migrations.RenameField(
            model_name='listpatpagetwo',
            old_name='TransferFrom',
            new_name='transfer_from',
        ),
    ]
