# Generated by Django 3.2.9 on 2021-12-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ListOfPatients', '0006_auto_20211212_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listpatview',
            name='date_arrived',
            field=models.DateField(db_index=True, null=True, verbose_name='Дата поступления'),
        ),
        migrations.AlterField(
            model_name='listpatview',
            name='date_released',
            field=models.DateField(db_index=True, null=True, verbose_name='Дата выписки'),
        ),
    ]
